<?php

return [

    'navigation' => [
        'label' => 'Expenses Report',
        'group' => 'Booking Management',
    ],

    'title' => 'Expenses Report',
    'document_title' => 'Official Expenses Report',

    'filters' => [
        'period' => 'Period',
        'event' => 'Event',
        'all_events' => 'All Events',
        'category' => 'Category',
        'all_categories' => 'All Categories',
        'type' => 'Expense Type',
        'all_types' => 'All Types',
        'payment_status' => 'Payment Status',
        'all_statuses' => 'All Statuses',
        'date_from' => 'From Date',
        'date_to' => 'To Date',
        'language' => 'Report Language',
    ],

    'periods' => [
        'today' => 'Today',
        'this_week' => 'This Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'this_year' => 'This Year',
        'custom' => 'Custom Range',
    ],

    'languages' => [
        'en' => 'English',
        'ar' => 'Arabic',
    ],

    'sections' => [
        'filters' => 'Filters',
        'summary' => 'Summary',
        'expense_trend' => 'Expense Trend',
        'by_category' => 'Expenses by Category',
        'by_type' => 'Expenses by Type',
        'by_event' => 'Expenses by Event',
        'by_payment_status' => 'Expenses by Payment Status',
    ],

    'stats' => [
        'total_amount' => 'Total Expenses',
        'total_tax' => 'Total Tax',
        'total_paid' => 'Total Paid',
        'total_pending' => 'Total Pending',
        'expense_count' => 'Number of Expenses',
        'avg_expense' => 'Average Expense',
    ],

    'columns' => [
        'date' => 'Date',
        'category' => 'Category',
        'type' => 'Type',
        'event' => 'Event',
        'payment_status' => 'Payment Status',
        'count' => 'Count',
        'amount' => 'Amount',
    ],

    'currency' => 'OMR',

    'uncategorized' => 'Uncategorized',

    'actions' => [
        'download_pdf' => 'Download PDF',
        'download_csv' => 'Download CSV',
        'download_excel' => 'Download Excel',
    ],

    'export' => [
        'filename' => 'expenses-report',
    ],

    'document' => [
        'generated_on' => 'Generated on',
        'period_label' => 'Reporting Period',
        'period' => ':from — :to',
        'page' => 'Page',
        'confidential' => 'Official Document — Generated by the Booking Management System',
    ],

    'no_data' => 'No expense data available for the selected period.',

];
