<?php

return [

    'navigation' => [
        'label' => 'Financial Report',
        'group' => 'Booking Management',
    ],

    'title' => 'Financial Report',
    'document_title' => 'Official Financial Report',

    'filters' => [
        'period'     => 'Period',
        'event'      => 'Event',
        'all_events' => 'All Events',
        'event_date' => 'Event Date',
        'all_dates'  => 'All Dates',
        'time_slot'  => 'Time Slot',
        'all_slots'  => 'All Slots',
        'date_from'  => 'From Date',
        'date_to'    => 'To Date',
        'language'   => 'Report Language',
    ],

    'periods' => [
        'today'      => 'Today',
        'this_week'  => 'This Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'this_year'  => 'This Year',
        'custom'     => 'Custom Range',
    ],

    'languages' => [
        'en' => 'English',
        'ar' => 'Arabic',
    ],

    'sections' => [
        'filters'           => 'Filters',
        'summary'           => 'Summary',
        'revenue_trend'     => 'Revenue Trend',
        'by_ticket'         => 'Revenue by Ticket Type',
        'by_event'          => 'Revenue by Event',
        'by_payment_method' => 'Revenue by Payment Method',
    ],

    'stats' => [
        'total_revenue'   => 'Total Revenue',
        'total_paid'      => 'Total Paid',
        'balance_due'     => 'Balance Due',
        'total_bookings'  => 'Total Bookings',
        'avg_booking'     => 'Average Booking Value',
    ],

    'payment_methods' => [
        'cash'        => 'Cash',
        'credit_debit' => 'Credit / Debit Card',
        'partial'     => 'Partial Payment',
    ],

    'columns' => [
        'date'           => 'Date',
        'ticket_type'    => 'Ticket Type',
        'event'          => 'Event',
        'payment_method' => 'Payment Method',
        'bookings'       => 'Bookings',
        'revenue'        => 'Revenue',
        'percentage'     => 'Percentage',
    ],

    'currency' => 'OMR',

    'actions' => [
        'download_pdf'   => 'Download PDF',
        'download_csv'   => 'Download CSV',
        'download_excel' => 'Download Excel',
    ],

    'export' => [
        'filename' => 'financial-report',
    ],

    'document' => [
        'generated_on' => 'Generated on',
        'period_label' => 'Reporting Period',
        'period'       => ':from — :to',
        'page'         => 'Page',
        'confidential' => 'Official Document — Generated by the Booking Management System',
    ],

    'no_data' => 'No financial data available for the selected period.',

];
