<?php

return [

    'navigation' => [
        'label' => 'Visitor Report',
        'group' => 'Booking Management',
    ],

    'title' => 'Visitor Report',
    'document_title' => 'Official Visitor Report',

    'filters' => [
        'period'     => 'Period',
        'event'      => 'Event',
        'all_events' => 'All Events',
        'event_date' => 'Event Date',
        'all_dates'  => 'All Dates',
        'time_slot'  => 'Time Slot',
        'all_slots'  => 'All Slots',
        'date_from'  => 'From Date',
        'date_to'    => 'To Date',
        'language'   => 'Report Language',
    ],

    'periods' => [
        'today'      => 'Today',
        'this_week'  => 'This Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'this_year'  => 'This Year',
        'custom'     => 'Custom Range',
    ],

    'languages' => [
        'en' => 'English',
        'ar' => 'Arabic',
    ],

    'sections' => [
        'filters'       => 'Filters',
        'summary'       => 'Summary',
        'by_gender'     => 'Visitors by Gender',
        'by_ticket'     => 'Visitors by Ticket Type',
        'by_time_slot'  => 'Visitors by Time Slot',
        'by_country'    => 'Visitors by Country',
    ],

    'stats' => [
        'total_visitors' => 'Total Visitors',
        'total_bookings' => 'Total Bookings',
        'checked_in'     => 'Checked In',
        'events_covered' => 'Events Covered',
    ],

    'gender' => [
        'male'        => 'Male',
        'female'      => 'Female',
        'unspecified' => 'Unspecified',
    ],

    'columns' => [
        'gender'      => 'Gender',
        'count'       => 'Visitors',
        'percentage'  => 'Percentage',
        'ticket_type' => 'Ticket Type',
        'time_slot'   => 'Time Slot',
        'country'     => 'Country',
        'other'       => 'Other',
    ],

    'actions' => [
        'download_pdf'   => 'Download PDF',
        'download_csv'   => 'Download CSV',
        'download_excel' => 'Download Excel',
    ],

    'export' => [
        'filename' => 'visitor-report',
    ],

    'document' => [
        'generated_on'  => 'Generated on',
        'period_label'  => 'Reporting Period',
        'period'        => ':from — :to',
        'page'          => 'Page',
        'confidential'  => 'Official Document — Generated by the Booking Management System',
    ],

    'no_data' => 'No visitor data available for the selected period.',

];
