@php
    $isRtl = ($locale ?? 'en') === 'ar';
@endphp
<!DOCTYPE html>
<html dir="{{ $isRtl ? 'rtl' : 'ltr' }}">
<head>
@include('reports.partials.pdf-fonts')
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
        font-family: 'Almarai', 'Segoe UI', Tahoma, Arial, sans-serif;
        font-size: 8px;
        color: #6b7280;
        width: 100%;
        padding: 0 12mm;
    }
    .footer-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-top: 1px solid #e5e7eb;
        padding-top: 4px;
    }
</style>
</head>
<body>
    <div class="footer-row">
        <span>{{ $isRtl ? 'وثيقة رسمية — تم إنشاؤها بواسطة نظام إدارة الحجوزات' : 'Official Document — Generated by the Booking Management System' }}</span>
        <span>{{ $isRtl ? 'صفحة' : 'Page' }} <span class="pageNumber"></span> / <span class="totalPages"></span></span>
    </div>
</body>
</html>
